"""Add total_max_spots column

Revision ID: 854657e11201
Revises: 
Create Date: 2025-04-24 14:42:46.144007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '854657e11201'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_class', schema=None) as batch_op:
        op.add_column('course_class', sa.Column('total_max_spots', sa.Integer(), nullable=False, server_default='0'))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_class', schema=None) as batch_op:
        batch_op.drop_column('total_max_spots')

    # ### end Alembic commands ###
